import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import ConfidenceBar from "./ConfidenceBar";

type Props = {
  prediction: string;
  confidence: number;
  ai_info: string;
};

export default function ResultCard({
  prediction,
  confidence,
  ai_info,
}: Props) {
  return (
    <div className="space-y-6">

      <div className="rounded-3xl border border-zinc-800 bg-zinc-900/70 p-8 backdrop-blur-xl">

        <p className="text-sm uppercase tracking-wider text-cyan-400">
          Prediction Result
        </p>

        <h2 className="mt-3 text-5xl font-black capitalize bg-gradient-to-r from-cyan-300 to-purple-400 bg-clip-text text-transparent">
          {prediction}
        </h2>

        <div className="mt-6">
          <ConfidenceBar confidence={confidence} />

          <p className="mt-4 text-sm text-zinc-400">
            {
                confidence >= 90
                ? "Excellent Prediction"
                : confidence >= 75
                ? "Good Prediction"
                : confidence >= 60
                ? "Moderate Prediction"
                : "Low Confidence"
            }
          </p>
        </div>

      </div>

      <div className="rounded-3xl border border-zinc-800 bg-zinc-900/70 p-8 backdrop-blur-xl">

        <div className="mb-8 flex items-center gap-3">

            <div className="h-10 w-1 rounded-full bg-gradient-to-b from-cyan-400 to-purple-500" />

            <div>
                <h3 className="text-2xl font-bold">
                AI Insights
                </h3>

                <p className="text-sm text-zinc-400">
                Generated by Gemini AI
                </p>
            </div>

            </div>

        <div
            className="
                prose
                prose-invert
                max-w-none

                prose-headings:text-cyan-300
                prose-headings:font-bold

                prose-h1:text-4xl
                prose-h1:mb-8
                prose-h1:bg-gradient-to-r
                prose-h1:from-cyan-300
                prose-h1:to-purple-400
                prose-h1:bg-clip-text
                prose-h1:text-transparent

                prose-h2:mt-10
                prose-h2:mb-5
                prose-h2:border-b
                prose-h2:border-cyan-500/20
                prose-h2:pb-3

                prose-h3:mt-8
                prose-h3:mb-4

                prose-p:leading-8
                prose-p:mb-5
                prose-p:text-zinc-300

                prose-ul:my-5
                prose-li:mb-3

                prose-strong:text-cyan-200
            "
            >
            <div
                className="
                    prose
                    prose-invert
                    max-w-none

                    prose-headings:text-cyan-300
                    prose-headings:font-bold

                    prose-h1:text-4xl
                    prose-h1:mb-8
                    prose-h1:bg-gradient-to-r
                    prose-h1:from-cyan-300
                    prose-h1:to-purple-400
                    prose-h1:bg-clip-text
                    prose-h1:text-transparent

                    prose-h2:mt-10
                    prose-h2:mb-5
                    prose-h2:border-b
                    prose-h2:border-cyan-500/20
                    prose-h2:pb-3

                    prose-h3:mt-8
                    prose-h3:mb-4

                    prose-p:leading-8
                    prose-p:mb-5
                    prose-p:text-zinc-300

                    prose-ul:my-5
                    prose-li:mb-3

                    prose-strong:text-cyan-200
                "
                >
            </div>

            <div className="mb-8 rounded-2xl border border-cyan-500/20 bg-cyan-500/10 p-4">
                <p className="text-sm font-semibold text-cyan-300">
                    AI Generated Biological Analysis
                </p>

                <p className="mt-1 text-xs text-zinc-400">
                    Taxonomy • Habitat • Characteristics • Fun Facts
                </p>
            </div>

          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {ai_info}
          </ReactMarkdown>
        </div>

      </div>

    </div>
  );
}